"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpsertHouseArgs = exports.UpdateManyHouseArgs = exports.UpdateHouseArgs = exports.FindUniqueHouseArgs = exports.FindManyHouseArgs = exports.FindFirstHouseArgs = exports.DeleteManyHouseArgs = exports.DeleteHouseArgs = exports.CreateHouseArgs = exports.AggregateHouseArgs = void 0;
var AggregateHouseArgs_1 = require("./AggregateHouseArgs");
Object.defineProperty(exports, "AggregateHouseArgs", { enumerable: true, get: function () { return AggregateHouseArgs_1.AggregateHouseArgs; } });
var CreateHouseArgs_1 = require("./CreateHouseArgs");
Object.defineProperty(exports, "CreateHouseArgs", { enumerable: true, get: function () { return CreateHouseArgs_1.CreateHouseArgs; } });
var DeleteHouseArgs_1 = require("./DeleteHouseArgs");
Object.defineProperty(exports, "DeleteHouseArgs", { enumerable: true, get: function () { return DeleteHouseArgs_1.DeleteHouseArgs; } });
var DeleteManyHouseArgs_1 = require("./DeleteManyHouseArgs");
Object.defineProperty(exports, "DeleteManyHouseArgs", { enumerable: true, get: function () { return DeleteManyHouseArgs_1.DeleteManyHouseArgs; } });
var FindFirstHouseArgs_1 = require("./FindFirstHouseArgs");
Object.defineProperty(exports, "FindFirstHouseArgs", { enumerable: true, get: function () { return FindFirstHouseArgs_1.FindFirstHouseArgs; } });
var FindManyHouseArgs_1 = require("./FindManyHouseArgs");
Object.defineProperty(exports, "FindManyHouseArgs", { enumerable: true, get: function () { return FindManyHouseArgs_1.FindManyHouseArgs; } });
var FindUniqueHouseArgs_1 = require("./FindUniqueHouseArgs");
Object.defineProperty(exports, "FindUniqueHouseArgs", { enumerable: true, get: function () { return FindUniqueHouseArgs_1.FindUniqueHouseArgs; } });
var UpdateHouseArgs_1 = require("./UpdateHouseArgs");
Object.defineProperty(exports, "UpdateHouseArgs", { enumerable: true, get: function () { return UpdateHouseArgs_1.UpdateHouseArgs; } });
var UpdateManyHouseArgs_1 = require("./UpdateManyHouseArgs");
Object.defineProperty(exports, "UpdateManyHouseArgs", { enumerable: true, get: function () { return UpdateManyHouseArgs_1.UpdateManyHouseArgs; } });
var UpsertHouseArgs_1 = require("./UpsertHouseArgs");
Object.defineProperty(exports, "UpsertHouseArgs", { enumerable: true, get: function () { return UpsertHouseArgs_1.UpsertHouseArgs; } });
